path_to_json = './service_account_configs/sinani-inventory-app-f8383390239a.json'
sheet_key = '1yyLl9NVVljNXrKg4Kjr_0hEum1Bv0B55x5Bgs2m1_tM'
sheet_name = 'Stock in Demo'
path_to_names = './stock_in_configs/names.csv'
path_to_suppliers = './stock_in_configs/suppliers.csv'
path_to_stock_units = './stock_in_configs/stock_units.csv'
